image_acquisition:
  input_type: "camera_usb" #camera_usb, video
  
  camera_usb: 
      camera_node: 1
  
  video:
      video_node: 1
      video_path_0: "/home/nullbyte/Desktop/myGit/ROS_Basics/ROS1/test_data/video/test_1.mp4"
  
  frequency: 10